const MOCK_EVENTS = [
  {
    id: 'evt-001',
    eventoId: 'INC-2026-001',
    tipoEvento: 'incentivo',
    status: 'em_andamento',
    clienteId: 'cli-001',
    atendimento: 'Harle da Costa',
    solicitante: 'Harle da Costa',
    produto: 'Momenta 10mg',
    dataSolicitacao: '2026-06-20',
    nomeEvento: 'Jantar Médico Araxá',
    data: '2026-06-25',
    horario: '19:30',
    nomeRestaurante: 'Samthiago Bistrô',
    valorPorPessoa: 248.00,
    numeroParticipantes: 15,
    cidade: 'Araxá',
    estado: 'MG',
    endereco: 'Av. Sen. Montandom 340',
    contatoRestauranteNome: 'Samuel',
    contatoRestauranteTelefone: '(34) 9 9940-5636',
    medico: 'Marcelo Miguel Hueb',
    telefoneMedico: '(34) 99972-3636',
    emailMedico: 'mmhueb@gmail.com',
    feeMedico: 800.00,
    extras: [
      { id: 'ext-1', tipo: 'Material', descricao: 'Folder e material gráfico', quantidade: 1, valorUnitario: 350, valor: 350 }
    ]
  },
  {
    id: 'evt-002',
    eventoId: 'EVT-2026-001',
    tipoEvento: 'evento',
    status: 'aguardando_aprovacao',
    clienteId: 'cli-002',
    atendimento: 'Ana Paula Silva',
    solicitante: 'Fernanda Lima',
    produto: 'PharmaX',
    dataSolicitacao: '2026-06-18',
    nomeEvento: 'Almoço Villa Roma',
    data: '2026-07-10',
    horario: '12:00',
    nomeRestaurante: 'Restaurante Villa Roma',
    valorPorPessoa: 185.00,
    numeroParticipantes: 20,
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    endereco: 'Rua Visconde de Pirajá 580',
    contatoRestauranteNome: 'Marcos',
    contatoRestauranteTelefone: '(21) 3542-8890',
    medico: 'Dr. Ricardo Alves',
    telefoneMedico: '(21) 98765-4321',
    emailMedico: 'ricardo.alves@medmail.com',
    feeMedico: 600.00,
    extras: []
  },
  {
    id: 'evt-003',
    eventoId: 'INC-2026-002',
    tipoEvento: 'incentivo',
    status: 'concluido',
    clienteId: 'cli-003',
    atendimento: 'Harle da Costa',
    solicitante: 'Patricia Souza',
    produto: 'LabMed 5mg',
    dataSolicitacao: '2026-05-10',
    nomeEvento: 'Jantar Casa do Chef',
    data: '2026-05-28',
    horario: '20:00',
    nomeRestaurante: 'Casa do Chef',
    valorPorPessoa: 320.00,
    numeroParticipantes: 12,
    cidade: 'Belo Horizonte',
    estado: 'MG',
    endereco: 'Av. do Contorno 6050',
    contatoRestauranteNome: 'Carla',
    contatoRestauranteTelefone: '(31) 3333-2211',
    medico: 'Dra. Juliana Martins',
    telefoneMedico: '(31) 99888-7766',
    emailMedico: 'juliana.martins@hospital.com',
    feeMedico: 500.00,
    extras: [
      { id: 'ext-2', tipo: 'Serviço', descricao: 'Coffee break extra', quantidade: 2, valorUnitario: 140, valor: 280 }
    ]
  },
  {
    id: 'evt-004',
    eventoId: 'MEE-2026-001',
    tipoEvento: 'meet',
    status: 'aberto',
    clienteId: 'cli-004',
    atendimento: 'Ana Paula Silva',
    solicitante: 'Lucas Ferreira',
    produto: 'BioCell',
    dataSolicitacao: '2026-06-28',
    nomeEvento: 'Meet Bistrô Jardins',
    data: '2026-07-20',
    horario: '18:30',
    nomeRestaurante: 'Bistrô Jardins',
    valorPorPessoa: 210.00,
    numeroParticipantes: 18,
    cidade: 'São Paulo',
    estado: 'SP',
    endereco: 'Alameda Santos 1200',
    contatoRestauranteNome: 'Paulo',
    contatoRestauranteTelefone: '(11) 3456-7890',
    medico: 'Dr. Eduardo Campos',
    telefoneMedico: '(11) 91234-5678',
    emailMedico: 'eduardo.campos@clinica.com',
    feeMedico: 700.00,
    extras: []
  },
  {
    id: 'evt-005',
    eventoId: 'EST-2026-001',
    tipoEvento: 'estande',
    status: 'cancelado',
    clienteId: 'cli-005',
    atendimento: 'Harle da Costa',
    solicitante: 'Mariana Costa',
    produto: 'FarmaSC Plus',
    dataSolicitacao: '2026-05-01',
    nomeEvento: 'Estande Farma SC',
    data: '2026-05-15',
    horario: '19:00',
    nomeRestaurante: 'Marisqueira do Porto',
    valorPorPessoa: 195.00,
    numeroParticipantes: 10,
    cidade: 'Florianópolis',
    estado: 'SC',
    endereco: 'Rua Felipe Schmidt 200',
    contatoRestauranteNome: 'Recepção',
    contatoRestauranteTelefone: '(48) 3222-1100',
    medico: 'Dr. Paulo Henrique',
    telefoneMedico: '(48) 99111-2233',
    emailMedico: 'paulo.henrique@med.com',
    feeMedico: 0,
    extras: [
      { id: 'ext-3', tipo: 'Locação', descricao: 'Montagem estande', quantidade: 1, valorUnitario: 4500, valor: 4500 }
    ]
  }
];
